application: gatwitbot
version: '2014-04'
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*/favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /static
  static_dir: static

- url: .*
  script: main.app

inbound_services:
- warmup

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest

error_handlers:
- file: templates/default_error.html

skip_files: |
 ^(.*/)?(
 (.*\.py[co])|
 (\..*)|
 (.*\.less)
 )$